# Generated by Django 3.0.7 on 2020-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название Новости')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.TextField(verbose_name='Текст')),
                ('isHidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок Объявления')),
                ('dateSTART', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала показа')),
                ('post', models.TextField(verbose_name='Текст')),
                ('isHidden', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, height_field=601, upload_to='', verbose_name='Превью 600x600', width_field=601)),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
            },
        ),
    ]
