# Generated by Django 3.0.7 on 2020-06-22 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_auto_20200622_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True, verbose_name='Дaта и время получения')),
                ('isMarkRead', models.BooleanField(default=False)),
                ('title', models.TextField(default='Заголовок уведомления', max_length=120)),
                ('text', models.TextField(default='Текст уведомления', max_length=500)),
                ('link', models.URLField(blank=True, default='localhost:8000:/dashboard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
