# Generated by Django 3.0.7 on 2020-06-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Уведомление для пользователя', 'verbose_name_plural': 'Уведомления для пользователя'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль для пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
